### ISSUE TITLE
Allow to specify Slack channel name via parameter

### ISSUE THREAD

**Issue by maximkrusina** [foo-software/lighthouse-check#36]
In case we have lot of projects, this will be very usefull, coz each project have it's corresponding SLack log channel. Thnax a lot!

**Comment by adamhenson** [comment]
Hi @maximkrusina - thanks for opening this. I'm not so sure I understand - could you re-phrase or elaborate?

This project allows you to specify a Slack Webhook URL as the [`slackWebhookUrl` param](https://github.com/foo-software/lighthouse-check#implementing-with-slack). When you [create a Webhook](https://api.slack.com/messaging/webhooks#create_a_webhook), you can specify the channel.

Are asking for a feature that will allow a different Slack Webhook for each URL?

If I understand the problem you could just call the function separately for each URL:

```javascript
import { lighthouseCheck } from '@foo-software/lighthouse-check';

(async () => {
  const response = await lighthouseCheck({
    slackWebhookUrl: 'https://www.webhook-1.com',
    urls: ['https://www.github.com']
  });

  console.log('response', response);

  const response2 = await lighthouseCheck({
    slackWebhookUrl: 'https://www.webhook-2.com',
    urls: ['https://www.google.com']
  });

  console.log('response 2', response2);
})();
```
