### ISSUE TITLE
Improvements discussion

### ISSUE THREAD

**Issue by eric-taix** [foo-software/lighthouse-check#5]
First very good job, I'm using your Github action to audit each PR deployed on Netlify for a side project to verify that there's no performance, accessibillity regression and it works fine. 👏 👏 👏 

I'm using the comment PR to be able to see the current value (even if all scores are higher than 90). For now I've only 5 urls to checks, but here's what could be improved in my point of view: this is a start of a discussion, to have your feedback and if you accept pull requests (didn't see any contribution page).

1- Urls are difficult to configure because this is a string with a comma separator. I think it could be easier if we can also configure urls with the following way:
```
  urls: |
    https://my-first-url
    https://my-second-url
    https://my-third-url
```
2- The comment added to the PR is a vertical table. Did you envisage to use a horizontal table ?
| | | | | |
|:---------:|:-------------:|:-----:|:----:|:----:|
| Performance | Accessibility | Best Practices | SEO | PWA |
| 92 | 87  | 100 | 100 | 0 |
> Unfortunately not sure there's a way to remove the header row but it takes less height than a vertical table

3- Another way to render scores could be to use badge, which by the way can use colors
![](https://img.shields.io/badge/Performance-45-red?style=flat-square) ![](https://img.shields.io/badge/Accessibility-92-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-97-green?style=flat-square) ![](https://img.shields.io/badge/SEO-65-orange?style=flat-square) ![](https://img.shields.io/badge/PWA-0-inactive?style=flat-square)

So let me know what are you thinking about these suggestions. And if you think that one/some of these suggestions could be implemented, do you accept PR? 
What is the workflow ? You create an issue first...

Thanks again for your work

**Comment by adamhenson** [comment]
Thanks @eric-taix. These are great suggestions. I'd be appreciative of any PRs. No need to create separate issues, but you could perhaps reference this one. I'm going to keep this open for a bit and invite any further discussion.

**Comment by adamhenson** [comment]
I love the badge idea. I'll take a crack at it today and let you know how far I get.

**Comment by eric-taix-teads** [comment]
Great 👍 

Just found `quickchart` today and you can generate a radial gauge with an image tag, so it's compliant with markdown image:
```
![Performance](https://quickchart.io/chart?c={type:%27radialGauge%27,data:{datasets:[{data:[60],backgroundColor:%27orange%27}]}})
``` 
generates
![Performance](https://quickchart.io/chart?c={type:%27radialGauge%27,data:{datasets:[{data:[60],backgroundColor:%27orange%27}]}})

See https://quickchart.io/documentation#radial-gauge

Licence & rate limiting must be checked before using it but it could be even more visual

**Comment by adamhenson** [comment]
Interesting! I dabbled with Quickchart, but the images got blurry when using `width=50&height=50` params. I'm also hesitant to add too much style if things change in the future. I'm implementing badges in #11 if you're interested in reviewing @eric-taix-teads.

**Comment by adamhenson** [comment]
PR comments as badges has been released in the GitHub action project in [v1.0.7](https://github.com/foo-software/lighthouse-check-action/releases/tag/v1.0.7).

**Comment by adamhenson** [comment]
After looking into the `urls` input, I've decided keep as a comma-separated string for now. The ideal solution would be a [YAML sequence](https://yaml.org/spec/1.2/spec.html#id2802662), but apparently inputs can only be strings:

> Action inputs only supports string keys and string values at this time. This is because they translate to environment variables within the action's execution run.

~ [GitHubCommunity Forum](https://github.community/t5/GitHub-Actions/Can-action-inputs-be-arrays/td-p/33776)

I think this is a flaw in GitHub Actions and will keep as is until the flaw is addressed 🤞

The suggestion [from Eric](https://github.com/foo-software/lighthouse-check/issues/5#issue-566427981) would work, however we'd need to parse the string for line breaks and I don't think it's a good permanent solution without a standardized type. The risk would come in implementation flaws (whitespace, etc).

**Comment by adamhenson** [comment]
Closing this issue as all discussion points have been addressed. More topics, feature requests, discussions are welcomed as new issues. Thanks!
