### ISSUE TITLE
prCommentAccessToken invalid input

### ISSUE THREAD

**Issue by yuchant** [foo-software/lighthouse-check#61]
I'm getting this error:

![image](https://user-images.githubusercontent.com/292732/151139034-dc923500-415f-49f3-89b5-f31ab310d8ee.png)

Sounds like accessToken, and githubAccessToken are the other access tokens. I'll try both..

Docs say prCommentAccessToken

**Comment by adamhenson** [comment]
Hi @yuchant - I don’t understand the issue. `prCommentAccessToken` is a valid option in this library. Your screenshot shows a warning in the GitHub Action. The GitHub Action documents valid inputs that might use different names when compared to this project.

Please refer to documentation in the Lighthouse Check GitHub Action project and if you run into problems - please open an issue in that project clearly stating the problem.

**Comment by adamhenson** [comment]
FWIW - in the GitHub Action project input names changed. I try not to introduce breaking changes so old names are still supported but you may see warnings (it’s not an error though).

This can happen if you don’t pin versions and use `@master`.
