### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module 

### ISSUE THREAD

**Issue by patdnr** [foo-software/lighthouse-check#77]
My Lighthouse test passed 2 days before, but now I am getting ERR_REQUIRE_ESM error.  This is the run: https://github.com/gaepdit/enforcement-orders/actions/runs/3534096869/jobs/5930723851. What should I do to fix it?

**Comment by adamhenson** [comment]
Hi @patdnr - sorry for this issue. We upgraded dependencies today, some of which appear to have been exported in ESM format, which we don't support.

I just made [a fix](https://github.com/foo-software/lighthouse-check/commit/b2a64c260279e496dd60992fd207e2ee5134d652) and published `@foo-software/lighthouse-check@8.0.9` which should fix your issue (the latest).

Could you try again, and let me know?

**Comment by patdnr** [comment]
You fixed the ERR_REQUIRE_ESM error. However, I am getting another error message ECONNREFUSED https://github.com/gaepdit/enforcement-orders/actions/runs/3534455038/jobs/5931342468

**Comment by adamhenson** [comment]
This issue means that your host is not accessible from where Lighthouse is running from. Nothing has changed from our end that would cause that and I'm not able to reproduce as its specific to your environment.

Have you seen this one before? I would use a `curl` command or something of that nature to test that the URL you're expecting is accessible. Feel free to let me know how it goes.

**Comment by adamhenson** [comment]
If this continues to be an issue for you, I would recommend pinning the GitHub Action you use at version 7.

**Comment by adamhenson** [comment]
@patdnr - FWIW, I see this in the logs of your run
```
lighthouse-check: Auditing desktop (1/6): https://localhost:44331
```
Which makes me think you're targeting port `44331`.

While further down we see the error coming from port `localhost:4000` which you have Lighthouse running against.

```
Error: connect ECONNREFUSED 127.0.0.1:4000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: [40](https://github.com/gaepdit/enforcement-orders/actions/runs/3534455038/jobs/5931342468#step:9:41)00
}
```

**Comment by patdnr** [comment]
Yea that is weird. Do you have an idea on why it's doing that? I check my workflow file and I never have port 4000 in there. This error only occurs after all websites was checked, so I think this might be something on the side of sending results to the pull request comment

**Comment by adamhenson** [comment]
I would need to see your code. Can you post it?

**Comment by patdnr** [comment]
I am not sure what you meant. 

I think that something has gone wrong in the lighthouse-check-status.js file. I got an error while Lighthouse Audit is running (specifically https://github.com/foo-software/lighthouse-check/blob/master/src/bin/lighthouse-check-status.js#L56). Did you only update the packages from version 7.0 to 8.0.9?

**Comment by adamhenson** [comment]
We released major version 8 today.

I would need to see your code to give you any advice. I'm completely blind to how you are using this project and therefore, I have no idea what could be causing your error.

**Comment by adamhenson** [comment]
My naive hunch is there is something malformed about the `prCommentUrl`.

**Comment by adamhenson** [comment]
Or that could be the browser port and it just means that the Chrome Browser is failing.

I'd strongly recommend taking a debug step and add to the workflow, something along the lines of `curl https://localhost:44331`

**Comment by patdnr** [comment]
> My naive hunch is there is something malformed about the `prCommentUrl`.

I checked that by removing the PR comment portion and it still gives that error, so it most likely is not that. https://github.com/gaepdit/enforcement-orders/actions/runs/3534955123/jobs/5932429985

The problem with `curl https://localhost:44331` is that I will for sure get an SSL certificate error.

Let's try another approach. The main reason why I have to install foo-software/lighthouse-check through npm is because I want to post PR comment. From your Github Actions example (https://github.com/foo-software/lighthouse-check#implementing-with-github-actions), how do I add the link to the pull request issue similar to how I currently have it (i.e. --prCommentUrl "https://api.github.com/repos/gaepdit/enforcement-orders/pulls/$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')/reviews")

**Comment by adamhenson** [comment]
Your PR comment code looks right. There is something wrong with you app. It's not Lighthouse or this project.

I see in your run that 6 URLs are queued, but only 2 complete. So, I think the Chrome Browser that Lighthouse runs on is dying because one of your pages is failing.

For example, try with only this one page `https://localhost:44331`.

**Comment by patdnr** [comment]
This is interesting. Testing only one page works flawlessly (regardless of whether it is `https://localhost:44331/`, `https://localhost:44331/Search?Status=All&handler=search#search-results`, or `https://localhost:44331/Details/15`).

However, the error occurs when there are 2 or more links being tested. How can I fix this issue?

**Comment by adamhenson** [comment]
This is what I expected. It's not the number of pages that this can't handle. As I explained before, there is something specifically wrong with the pages your app are serving (the 2 you have listed after `https://localhost:44331`). It is crashing Lighthouse. As I said before, Lighthouse crashes before the end of the queue in your case. I see this typically when the web page crashes.

I'm going to lock this conversation since it is irrelevant to this project.

**Comment by adamhenson** [comment]
I'm not sure what was causing the problem @patdnr, but I don't have a means of troubleshooting such an app specific setup. If you are able to reproduce a problem that you can prove relates to this project, please do open another issue with details.

Since we fixed the original problem behind this issue, I'd rather not clutter things up here or spend more of my personal time. Good luck!
